### ISSUE TITLE
Reactive State Engine problem using TA module

### ISSUE THREAD

**Issue by vishvesh098** [dolphindb/release#2]
Hi, I am using latest version dolphinDB 2.00.1. 

I want to use Reactive State Engine in my project for Technical Analysis. But when I try to use it with your great TA module it does not work. The only way to use the TA module is to define them as Custom State Function.

As per my opinion the Reactive State Engine is mainly used for getting realtime Technical Analysis Calculations. So in my humble opinion you should support TA module with Reactive State Engine or at least provide Custom State Function definition for them. It would be very very helpful !

Please see this thread for detailed information. https://ask.dolphindb.net/question/890

Thank you and Reply Soon !

**Comment by hzwale** [comment]
The TA module already supports the Reactive State Engine.
