### ISSUE TITLE
dolphinDB for arm64

### ISSUE THREAD

**Issue by QGB** [dolphindb/release#4]
docker run -itd -p 8848:8848 -v /home/qgb:/home/qgb -v /mnt:/mnt dolphindb/dolphindb:v2.00.7
Unable to find image 'dolphindb/dolphindb:v2.00.7' locally
v2.00.7: Pulling from dolphindb/dolphindb
59bf1c3509f3: Pull complete
5093d3943721: Pull complete
57f2a52df81b: Pull complete
d9fb158f3610: Pull complete
e87be6f59ce2: Pull complete
Digest: sha256:48c5d13f3153f9a1e5f3239043d8d86062966b425e653a5e8705e6fd6eea18bd
Status: Downloaded newer image for dolphindb/dolphindb:v2.00.7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
c467f90ac7d0053743cdf5b47e3567b04a4b88472d7bd4e8bf7fb8c65f5cdcfc

**Comment by hzwale** [comment]
Please download dolphindb for arm64 from https://www.dolphindb.com/downloads/DolphinDB_ARM64_V2.00.8.zip

**Comment by QGB** [comment]
@hzwale dolphindb docker 有arm版的吗？ 

armv7l 呢？

**Comment by hzwale** [comment]
有arm版，请参阅https://gitee.com/dolphindb/dolphindb-k8s/blob/master/docker_single_deployment.md#dolphindb-docker-%E5%8D%95%E6%9C%BA%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88 2.2节。
