### ISSUE TITLE
Cannot recognize function mysql::connect

### ISSUE THREAD

**Issue by liuweibing7** [dolphindb/release#6]
dolphin 版本: DolphinDB_Linux64_V1.30.21.5
执行 mysql 连接时报错：Cannot recognize function mysql::connect
是不是该版本去掉了 mysql::connect 函数？

**Comment by hzwale** [comment]
没有去掉，您可以在loadPlugin后执行defs(“mysql”)确认一下。
这个报错一般是loadPlugin后接着connect引起。建议在中间加一个go语句分段执行，例如：

loadPlugin("/path/to/plugins/mysql/PluginMySQL.txt")
go
conn = mysql::connect(`127.0.0.1, 3306, `root, `root, `DolphinDB)
